import { Trip, DayItinerary, Activity, DisruptionAlert, ReplanProposal } from '@/types/trip';

export const DEFAULT_SEMO_TRIP: Trip = {
  id: 'trip-seoul-demo-01',
  destination: 'Seoul',
  destinationCountry: 'South Korea',
  startDate: '2026-09-15',
  endDate: '2026-09-21',
  durationDays: 7,
  totalBudget: 80000,
  spentAmount: 52400,
  healthScore: 92,
  status: 'active',
  createdAt: '2026-08-24T10:00:00Z',
  updatedAt: '2026-08-24T10:00:00Z',
  preferences: {
    interests: ['culture', 'kpop', 'food', 'shopping', 'history', 'photography'],
    travelStyle: 'moderate',
    weatherSensitivity: 'high',
    pace: 'standard',
    budgetTotal: 80000,
    currency: 'INR (₹)',
  },
  days: [
    {
      day: 1,
      date: '2026-09-15',
      title: 'Arrival & Grand Royal Heritage',
      theme: 'Royal History & Hanok Culture',
      activities: [
        {
          id: 'act-d1-1',
          name: 'Gyeongbokgung Palace & Changing Guard',
          category: 'history',
          startTime: '10:00',
          endTime: '12:30',
          location: '161 Sajik-ro, Jongno-gu, Seoul',
          lat: 37.5796,
          lng: 126.9770,
          estimatedCost: 300,
          indoor: false,
          priority: 'high',
          description: 'Experience Joseon royal architecture and traditional hanbok wear in the historic palace courtyard.',
          imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&auto=format&fit=crop&q=80',
          travelTimeFromPreviousMin: 0
        },
        {
          id: 'act-d1-2',
          name: 'Tosokchon Samgyetang (Ginseng Chicken Lunch)',
          category: 'food',
          startTime: '13:00',
          endTime: '14:30',
          location: '5 Jahamun-ro 5-gil, Jongno-gu, Seoul',
          lat: 37.5778,
          lng: 126.9719,
          estimatedCost: 1400,
          indoor: true,
          priority: 'high',
          description: 'Famous historic eatery renowned for authentic bubbling ginseng chicken soup.',
          imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&auto=format&fit=crop&q=80',
          travelTimeFromPreviousMin: 12
        },
        {
          id: 'act-d1-3',
          name: 'Bukchon Hanok Village Walk',
          category: 'culture',
          startTime: '15:00',
          endTime: '17:00',
          location: '37 Gyedong-gil, Jongno-gu, Seoul',
          lat: 37.5826,
          lng: 126.9835,
          estimatedCost: 0,
          indoor: false,
          priority: 'medium',
          description: 'Picturesque residential neighborhood featuring 600-year-old preserved traditional Korean hanok houses.',
          imageUrl: 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=800&auto=format&fit=crop&q=80',
          travelTimeFromPreviousMin: 15
        },
        {
          id: 'act-d1-4',
          name: 'Insadong Traditional Tea House & Crafts',
          category: 'culture',
          startTime: '17:30',
          endTime: '19:30',
          location: 'Insadong-gil, Jongno-gu, Seoul',
          lat: 37.5744,
          lng: 126.9859,
          estimatedCost: 800,
          indoor: true,
          priority: 'medium',
          description: 'Artisan tea sampling, ceramic art browsing, and calligraphy galleries.',
          imageUrl: 'https://images.unsplash.com/photo-1535189043414-47a3c49a0bed?w=800&auto=format&fit=crop&q=80',
          travelTimeFromPreviousMin: 10
        }
      ]
    },
    {
      day: 2,
      date: '2026-09-16',
      title: 'Modern Marvels & High-Tech Seoul',
      theme: 'Architecture, Design & Gangnam Pulse',
      activities: [
        {
          id: 'act-d2-1',
          name: 'Dongdaemun Design Plaza (DDP)',
          category: 'architecture',
          startTime: '10:00',
          endTime: '12:30',
          location: '281 Eulji-ro, Jung-gu, Seoul',
          lat: 37.5668,
          lng: 127.0095,
          estimatedCost: 700,
          indoor: true,
          priority: 'high',
          description: 'Futuristic curved landmark by Zaha Hadid with design museum, runway hall, and artisan markets.',
          imageUrl: 'https://images.unsplash.com/photo-1546874177-9e664107314e?w=800&auto=format&fit=crop&q=80',
          travelTimeFromPreviousMin: 0
        },
        {
          id: 'act-d2-2',
          name: 'Gwangjang Market Street Food Tour',
          category: 'food',
          startTime: '13:00',
          endTime: '14:30',
          location: '88 Changgyeonggung-ro, Jongno-gu, Seoul',
          lat: 37.5700,
          lng: 126.9996,
          estimatedCost: 900,
          indoor: true,
          priority: 'high',
          description: 'Sizzle of freshly made bindaetteok (mungbean pancakes), mayak gimbap, and hand-cut kalguksu noodles.',
          imageUrl: 'https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=800&auto=format&fit=crop&q=80',
          travelTimeFromPreviousMin: 12
        },
        {
          id: 'act-d2-3',
          name: 'Apgujeong Rodeo & K-Star Road',
          category: 'kpop',
          startTime: '15:30',
          endTime: '18:00',
          location: 'Apgujeong-ro, Gangnam-gu, Seoul',
          lat: 37.5273,
          lng: 127.0396,
          estimatedCost: 1500,
          indoor: false,
          priority: 'medium',
          description: 'K-pop agency headquarters, designer fashion boutiques, and photo zones with idol mascot bears.',
          imageUrl: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80',
          travelTimeFromPreviousMin: 22
        }
      ]
    },
    {
      day: 3,
      date: '2026-09-17',
      title: 'Scenic Panorama & Youth Culture (Original Plan)',
      theme: 'Outdoor Nature, Skyline & Nightlife',
      activities: [
        {
          id: 'act-d3-1',
          name: 'Namsan Seoul Tower & Mountain Park',
          category: 'nature',
          startTime: '10:00',
          endTime: '12:30',
          location: '105 Namsangongwon-gil, Yongsan-gu, Seoul',
          lat: 37.5512,
          lng: 126.9882,
          estimatedCost: 800,
          indoor: false,
          priority: 'high',
          description: 'Panoramic outdoor summit trails, love locks observatory deck, and mountain breeze.',
          imageUrl: 'https://images.unsplash.com/photo-1538669715315-155099bfa88c?w=800&auto=format&fit=crop&q=80',
          travelTimeFromPreviousMin: 0
        },
        {
          id: 'act-d3-2',
          name: 'Myeongdong K-BBQ Lunch',
          category: 'food',
          startTime: '13:00',
          endTime: '14:30',
          location: 'Myeongdong 2-ga, Jung-gu, Seoul',
          lat: 37.5636,
          lng: 126.9856,
          estimatedCost: 1800,
          indoor: true,
          priority: 'high',
          description: 'Sizzling Korean pork belly and marinated galbi in central Myeongdong.',
          imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop&q=80',
          travelTimeFromPreviousMin: 20
        },
        {
          id: 'act-d3-3',
          name: 'Han River Yeouido Park & Picnic',
          category: 'nature',
          startTime: '15:00',
          endTime: '17:30',
          location: '330 Yeouidong-ro, Yeongdeungpo-gu, Seoul',
          lat: 37.5284,
          lng: 126.9341,
          estimatedCost: 400,
          indoor: false,
          priority: 'high',
          description: 'Open-air riverside picnic, bicycle riding along the riverbank, and scenic waterfront.',
          imageUrl: 'https://images.unsplash.com/photo-1548115184-bc6544d06a58?w=800&auto=format&fit=crop&q=80',
          travelTimeFromPreviousMin: 28
        },
        {
          id: 'act-d3-4',
          name: 'Hongdae Indie & Night Market Exploration',
          category: 'nightlife',
          startTime: '19:00',
          endTime: '22:00',
          location: 'Hongik Univ. Walk Street, Mapo-gu, Seoul',
          lat: 37.5563,
          lng: 126.9226,
          estimatedCost: 1500,
          indoor: true,
          priority: 'high',
          description: 'Bustling indie music clubs, street art, vibrant night cafes, and vintage thrifting.',
          imageUrl: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80',
          travelTimeFromPreviousMin: 26
        }
      ]
    },
    {
      day: 4,
      date: '2026-09-18',
      title: 'K-Wave & Digital Entertainment',
      theme: 'K-Pop, Virtual Realities & Gangnam',
      activities: [
        {
          id: 'act-d4-1',
          name: 'HiKR Ground K-Pop Experience Zone',
          category: 'kpop',
          startTime: '10:30',
          endTime: '12:30',
          location: '40 Cheonggyecheon-ro, Jung-gu, Seoul',
          lat: 37.5694,
          lng: 126.9818,
          estimatedCost: 0,
          indoor: true,
          priority: 'high',
          description: 'Multi-sensory interactive music video creation studio with customizable neon stages and XR tech.',
          imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80',
          travelTimeFromPreviousMin: 0
        },
        {
          id: 'act-d4-2',
          name: 'Gangnam Style Statue & Bongeunsa Temple',
          category: 'culture',
          startTime: '14:00',
          endTime: '16:30',
          location: '531 Bongeunsa-ro, Gangnam-gu, Seoul',
          lat: 37.5147,
          lng: 127.0573,
          estimatedCost: 0,
          indoor: false,
          priority: 'medium',
          description: 'Peaceful ancient Buddhist temple nestled directly amidst high-tech skyscrapers of Gangnam.',
          imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80',
          travelTimeFromPreviousMin: 28
        }
      ]
    },
    {
      day: 5,
      date: '2026-09-19',
      title: 'Art, Design & Trendy Seongsu',
      theme: 'Brooklyn of Seoul & Gourmet Cafes',
      activities: [
        {
          id: 'act-d5-1',
          name: 'Seongsu-dong Industrial Cafe Stroll',
          category: 'food',
          startTime: '11:00',
          endTime: '13:30',
          location: 'Seongsui-ro, Seongdong-gu, Seoul',
          lat: 37.5444,
          lng: 127.0560,
          estimatedCost: 1200,
          indoor: true,
          priority: 'high',
          description: 'Repurposed shoe factories transformed into aesthetic bakeries, concept stores, and Dior concept pop-up.',
          imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&auto=format&fit=crop&q=80',
          travelTimeFromPreviousMin: 0
        },
        {
          id: 'act-d5-2',
          name: 'Seoul Forest Park & Insect Garden',
          category: 'nature',
          startTime: '14:30',
          endTime: '17:00',
          location: '273 Ttukseom-ro, Seongdong-gu, Seoul',
          lat: 37.5443,
          lng: 127.0374,
          estimatedCost: 0,
          indoor: false,
          priority: 'medium',
          description: 'Sprawling eco-park with deer corral, sculpture walk, and tree-canopied trails.',
          imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&auto=format&fit=crop&q=80',
          travelTimeFromPreviousMin: 15
        }
      ]
    },
    {
      day: 6,
      date: '2026-09-20',
      title: 'Skyline Heights & Theme Park Thrills',
      theme: 'Mega Observation & Entertainment',
      activities: [
        {
          id: 'act-d6-1',
          name: 'Lotte World Tower Seoul Sky Observatory',
          category: 'architecture',
          startTime: '10:30',
          endTime: '13:00',
          location: '300 Olympic-ro, Songpa-gu, Seoul',
          lat: 37.5126,
          lng: 127.1025,
          estimatedCost: 2200,
          indoor: true,
          priority: 'high',
          description: 'Ascend to the 123rd floor for a 360-degree glass-floor observation experience above Seoul.',
          imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80',
          travelTimeFromPreviousMin: 0
        },
        {
          id: 'act-d6-2',
          name: 'Lotte World Adventure Indoor Park',
          category: 'relaxation',
          startTime: '14:00',
          endTime: '18:30',
          location: '240 Olympic-ro, Songpa-gu, Seoul',
          lat: 37.5111,
          lng: 127.0982,
          estimatedCost: 3500,
          indoor: true,
          priority: 'medium',
          description: 'Largest indoor theme park with rollercoasters, laser shows, and ice skating rink.',
          imageUrl: 'https://images.unsplash.com/photo-1513889961551-628c1e5e2ee9?w=800&auto=format&fit=crop&q=80',
          travelTimeFromPreviousMin: 8
        }
      ]
    },
    {
      day: 7,
      date: '2026-09-21',
      title: 'Farewell Seoul: Souvenirs & Spa Refresh',
      theme: 'Relaxation & Local Farewell',
      activities: [
        {
          id: 'act-d7-1',
          name: 'Cimer Paradise Spa & Jimjilbang',
          category: 'relaxation',
          startTime: '10:00',
          endTime: '13:00',
          location: 'Yeongjong-do, Incheon (En Route to Airport)',
          lat: 37.4646,
          lng: 126.4407,
          estimatedCost: 2800,
          indoor: true,
          priority: 'high',
          description: 'Luxury European-style aqua spa with heated mineral pools, dry steam saunas, and relaxation zones.',
          imageUrl: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop&q=80',
          travelTimeFromPreviousMin: 0
        },
        {
          id: 'act-d7-2',
          name: 'Incheon Airport Culture & Duty-Free Walk',
          category: 'shopping',
          startTime: '14:30',
          endTime: '17:00',
          location: '272 Gonghang-ro, Jung-gu, Incheon',
          lat: 37.4602,
          lng: 126.4407,
          estimatedCost: 1500,
          indoor: true,
          priority: 'high',
          description: 'Korean cultural street, souvenir shopping, and flight departure.',
          imageUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&auto=format&fit=crop&q=80',
          travelTimeFromPreviousMin: 15
        }
      ]
    }
  ]
};

export const REPLAN_DAY3_PROPOSAL: ReplanProposal = {
  id: 'replan-seoul-d3-rain',
  tripId: 'trip-seoul-demo-01',
  dayNumber: 3,
  disruptionAlertId: 'alert-rain-d3',
  title: '🌧️ Weather Replan: Shift Outdoor Activities to Cultural Indoor Spaces',
  summary: 'Replaced Namsan Park & Han River outdoor stops with National Museum of Korea and COEX Starfield Complex.',
  rationale: 'Heavy torrential rainfall (87% probability, ~24mm precipitation) is forecasted from 10:00 AM to 5:00 PM. Namsan Mountain trails and Han River open grounds have high slipping risks and zero rain shelter. Replaced with the National Museum of Korea (world-class indoor cultural exhibit, ₹0 entry) and COEX Mall & Starfield Library, reducing outdoor exposure from High to Low and cutting total transit travel time by 18 minutes while increasing cultural alignment to 94%.',
  changes: [
    {
      originalActivityId: 'act-d3-1',
      removed: 'Namsan Seoul Tower & Mountain Park',
      reason: 'Heavy rain & low cloud ceiling obscures skyline view and makes mountain paths slippery.',
      originalTime: '10:00 - 12:30',
      newTime: '10:00 - 12:30',
      preferenceMatchScore: 0.94,
      replacement: {
        id: 'act-d3-1-repl',
        name: 'National Museum of Korea',
        category: 'museum',
        startTime: '10:00',
        endTime: '12:30',
        location: '137 Seobinggo-ro, Yongsan-gu, Seoul',
        lat: 37.5239,
        lng: 126.9804,
        estimatedCost: 0,
        indoor: true,
        priority: 'high',
        description: 'World-class indoor national museum housing Korea\'s crown jewels, Goryeo celadon, and immersive 8K digital heritage hall.',
        imageUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80',
        travelTimeFromPreviousMin: 0
      }
    },
    {
      originalActivityId: 'act-d3-3',
      removed: 'Han River Yeouido Park & Picnic',
      reason: 'Outdoor riverbank winds and open lawns flooded during heavy rainstorm.',
      originalTime: '15:00 - 17:30',
      newTime: '15:00 - 17:30',
      preferenceMatchScore: 0.93,
      replacement: {
        id: 'act-d3-3-repl',
        name: 'COEX Mall & Starfield Giant Library',
        category: 'shopping',
        startTime: '15:00',
        endTime: '17:30',
        location: '513 Yeongdong-daero, Gangnam-gu, Seoul',
        lat: 37.5113,
        lng: 127.0594,
        estimatedCost: 1200,
        indoor: true,
        priority: 'high',
        description: 'Spectacular 13-meter high indoor bookshelf monument, cafe haven, K-pop popups, and climate-controlled shopping.',
        imageUrl: 'https://images.unsplash.com/photo-1596701062351-8c2c14d1fdd0?w=800&auto=format&fit=crop&q=80',
        travelTimeFromPreviousMin: 18
      }
    }
  ],
  metrics: {
    outdoorExposure: {
      original: 'High',
      proposed: 'Low',
    },
    totalCost: {
      original: 4500,
      proposed: 4500,
      delta: 0,
    },
    travelTimeMinutes: {
      original: 74,
      proposed: 56,
      delta: -18,
    },
    preferenceMatch: {
      original: 88,
      proposed: 94,
    }
  },
  proposedDayItinerary: {
    day: 3,
    date: '2026-09-17',
    title: 'Adaptive Indoor Culture & Vibrant Nightlife (AI Optimized)',
    theme: 'National Heritage & Starfield Experience',
    activities: [
      {
        id: 'act-d3-1-repl',
        name: 'National Museum of Korea',
        category: 'museum',
        startTime: '10:00',
        endTime: '12:30',
        location: '137 Seobinggo-ro, Yongsan-gu, Seoul',
        lat: 37.5239,
        lng: 126.9804,
        estimatedCost: 0,
        indoor: true,
        priority: 'high',
        description: 'World-class indoor national museum housing Korea\'s crown jewels, Goryeo celadon, and immersive 8K digital heritage hall.',
        imageUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80',
        travelTimeFromPreviousMin: 0
      },
      {
        id: 'act-d3-2',
        name: 'Myeongdong K-BBQ Lunch',
        category: 'food',
        startTime: '13:00',
        endTime: '14:30',
        location: 'Myeongdong 2-ga, Jung-gu, Seoul',
        lat: 37.5636,
        lng: 126.9856,
        estimatedCost: 1800,
        indoor: true,
        priority: 'high',
        description: 'Sizzling Korean pork belly and marinated galbi in central Myeongdong.',
        imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop&q=80',
        travelTimeFromPreviousMin: 16
      },
      {
        id: 'act-d3-3-repl',
        name: 'COEX Mall & Starfield Giant Library',
        category: 'shopping',
        startTime: '15:00',
        endTime: '17:30',
        location: '513 Yeongdong-daero, Gangnam-gu, Seoul',
        lat: 37.5113,
        lng: 127.0594,
        estimatedCost: 1200,
        indoor: true,
        priority: 'high',
        description: 'Spectacular 13-meter high indoor bookshelf monument, cafe haven, K-pop popups, and climate-controlled shopping.',
        imageUrl: 'https://images.unsplash.com/photo-1596701062351-8c2c14d1fdd0?w=800&auto=format&fit=crop&q=80',
        travelTimeFromPreviousMin: 18
      },
      {
        id: 'act-d3-4',
        name: 'Hongdae Indie & Night Market Exploration',
        category: 'nightlife',
        startTime: '19:00',
        endTime: '22:00',
        location: 'Hongik Univ. Walk Street, Mapo-gu, Seoul',
        lat: 37.5563,
        lng: 126.9226,
        estimatedCost: 1500,
        indoor: true,
        priority: 'high',
        description: 'Bustling indie music clubs, street art, vibrant night cafes, and vintage thrifting.',
        imageUrl: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80',
        travelTimeFromPreviousMin: 22
      }
    ]
  },
  createdAt: '2026-08-24T10:05:00Z',
  status: 'pending',
};
